### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by pallavjha25** [Saurabh3333/Login-Signup-Google-OAuth2#2]
When I tried running the program, I am getting runtime error.

Terminal->

node index.js 
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- /Users/username/Downloads/Login-Signup-Google-OAuth2-master/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/username/Downloads/Login-Signup-Google-OAuth2-master/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/username/Downloads/Login-Signup-Google-OAuth2-master/index.js'
  ]
}

**Comment by Saurabh3333** [comment]
Have you installed the 'express` module before running `node index.js`?

**Comment by pallavjha25** [comment]
No it was not initially. 
but just now I installed it after your response. and it is still throwing the same error:-
Terminal logs:-
Login-Signup-Google-OAuth2-master username$ node index.js 
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'passport'
Require stack:
- /Users/username/Downloads/Login-Signup-Google-OAuth2-master/routes/auth-routes.js
- /Users/username/Downloads/Login-Signup-Google-OAuth2-master/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/username/Downloads/Login-Signup-Google-OAuth2-master/routes/auth-routes.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/username/Downloads/Login-Signup-Google-OAuth2-master/routes/auth-routes.js',
    '/Users/username/Downloads/Login-Signup-Google-OAuth2-master/index.js'
  ]
}

**Comment by pallavjha25** [comment]
Here are the logs when I installed Express. Is there any error in this one ? 

machinename:Login-Signup-Google-OAuth2-master username$ npm install express --save
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/express failed, reason: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2019-10-09T07_42_10_243Z-debug.log
machinename:Login-Signup-Google-OAuth2-master username$ npm config set strict-ssl false
machinename:Login-Signup-Google-OAuth2-master username$ npm install express --save
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN login-signup@1.0.0 No repository field.

+ express@4.17.1
added 50 packages from 37 contributors and audited 126 packages in 5.015s
found 0 vulnerabilities

**Comment by Saurabh3333** [comment]
`Error: Cannot find module passport`. Install `passport` also. See `package.json` and first of all, install all the necessary modules.

**Comment by pallavjha25** [comment]
Thanks. I installed passport, and seems like it is now throwing error for ./keys. I have installed "npm install keys" and seems error for keys still there. Logs:- 
machinename:Login-Signup-Google-OAuth2-master username$ npm install keys
npm WARN login-signup@1.0.0 No repository field.

+ keys@0.1.2
added 1 package from 1 contributor and audited 140 packages in 1.019s
found 0 vulnerabilities

machinename:Login-Signup-Google-OAuth2-master username$ node index.js 
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module './keys'
Require stack:
- /Users/username/Downloads/Login-Signup-Google-OAuth2-master/config/passport-setup.js
- /Users/username/Downloads/Login-Signup-Google-OAuth2-master/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/username/Downloads/Login-Signup-Google-OAuth2-master/config/passport-setup.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/username/Downloads/Login-Signup-Google-OAuth2-master/config/passport-setup.js',
    '/Users/username/Downloads/Login-Signup-Google-OAuth2-master/index.js'
  ]
}



Is there a list of installing components liks, you can share in readme file? That will be great.

**Comment by Saurabh3333** [comment]
No need to install keys. For authentication we require a unique key provided my google developer tool. I have removed my personal keys for security. You need to generate your own key for authentication. 
I would suggest you to watch some videos related to this topic and then follow along. 

Thank you.
